# Generated by Django 4.1.7 on 2023-03-08 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="quanntity",
            new_name="quantity",
        ),
    ]
